### ISSUE TITLE
License problem, must release as GPL

### ISSUE THREAD

**Issue by alerque** [sabdelmalik/USFM-OSIS#1]
The GPL is a copy-left license and 'viral', not in the sense of sudden online popularity but in the sense that it infects everything it touches. You can't just base something else on it and release than new thing under a different license, you must keep the GPL intact on the new derivative. This includes reading the source of a GPL program and manually porting it to a different language with no direct code copy/paste.

The BSD license you have marked this repository under is not a valid choice since this repository is a derivative work of a GPL project.

**Comment by sabdelmalik** [comment]
Thanks,
My apologies for the ignorance.
Changed the license to GNU General Public License v3.0

**Comment by sabdelmalik** [comment]
Thank you very much Caleb,

 

My apologies, it is out of ignorance.

 

I’ve changed the license to, GNU General Public License v3.0.

 

Hope this makes things right.

 

All blessings

Sami

 

From: Caleb Maclennan ***@***.***> 
Sent: May 10, 2023 10:54 AM
To: sabdelmalik/USFM-OSIS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sabdelmalik/USFM-OSIS] License problem, must release as GPL (Issue #1)

 

The GPL is a copy-left license and 'viral', not in the sense of sudden online popularity but in the sense that it infects everything it touches. You can't just base something else on it and release than new thing under a different license, you must keep the GPL intact on the new derivative. This includes reading the source of a GPL program and manually porting it to a different language with no direct code copy/paste.

The BSD license you have marked this repository under is not a valid choice since this repository is a derivative work of a GPL project.

**Comment by alerque** [comment]
Thanks for addressing this, and no worries. Not everyone has had the misfortune of bumping into licensing issues and had to brush up on them.
